### ISSUE TITLE
[MINI-EPIC] View 1: People

### ISSUE THREAD

**Issue by bryankeane0** [bryankeane0/movie-app-v2#16]
**Describe the solution you'd like**
A new view with accompanying routes, endpoints and as-needed storybook support for new components for showing People (Actors & Actresses) and information on people. This will include a parameterized URL for individual people pages.

**Additional context**

**Tasks**
- [x] People view components
- [ ] Storybook
- [x] People API calls
- [x] People page
- [ ] People details page
- [x] Menu button for people
